# This file was generated by GoReleaser. DO NOT EDIT.
cask "envcore" do
  version "0.1.2"

  on_macos do
    on_intel do
      sha256 "0b683f4e5bcda420faae434a9ebf872672ba89cbc42e2dcf77632e6c44748645"
      url "https://github.com/yedidiaSch/envcore/releases/download/v#{version}/envcore_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "0ce52eea64947817216353376deb0734dce12685843516c7f2357c024d34316f"
      url "https://github.com/yedidiaSch/envcore/releases/download/v#{version}/envcore_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "9c256ae5add2d65735b7b2342263e3f9b5cd8bf1c85d3dee21804ad77decb709"
      url "https://github.com/yedidiaSch/envcore/releases/download/v#{version}/envcore_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "603cb55669ccff8686dbc1635ec0a1203dcca03647b4b54a6e8b5687c7da513e"
      url "https://github.com/yedidiaSch/envcore/releases/download/v#{version}/envcore_#{version}_linux_arm64.tar.gz"
    end
  end

  name "envcore"
  desc "Provision, harden & orchestrate C++/IPC dev environments"
  homepage "https://github.com/yedidiaSch/envcore"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "envcore"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/envcore"]
    end
  end

  # No zap stanza required

end
