# This file was generated by GoReleaser. DO NOT EDIT.
cask "pandion" do
  version "0.5.0"

  on_macos do
    on_intel do
      sha256 "b4566072ca5f6a522f62b295f92196439699ba02da34ff1058631de56567600f"
      url "https://github.com/yedidiaSch/pandion/releases/download/v#{version}/pandion_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "11008a456be561dd7440caeee5b3ee080ccb88d0a4cf90303628dde643c25dc6"
      url "https://github.com/yedidiaSch/pandion/releases/download/v#{version}/pandion_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "3e4db94b3f3b8288a53b3c605e215d105a2808faa8e0e5741dd234c359c3472a"
      url "https://github.com/yedidiaSch/pandion/releases/download/v#{version}/pandion_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "44e4938f947785495ea95f5c9c01ad3e3672681bb337ffdfc85cb10413e959ec"
      url "https://github.com/yedidiaSch/pandion/releases/download/v#{version}/pandion_#{version}_linux_arm64.tar.gz"
    end
  end

  name "pandion"
  desc "Provision, harden & orchestrate C++/IPC dev environments"
  homepage "https://github.com/yedidiaSch/pandion"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pandion"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/pandion"]
    end
  end

  # No zap stanza required

end
