# This file was generated by GoReleaser. DO NOT EDIT.
cask "pandion" do
  version "0.7.1"

  on_macos do
    on_intel do
      sha256 "d57681d4f22d12a148302af515e0ce85b617196486660c3eab98abc81f894665"
      url "https://github.com/yedidiaSch/pandion/releases/download/v#{version}/pandion_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "2d8e7f28f887dedd11196b59fc3854052ac6ec39812c832da9cada0cd0ce4492"
      url "https://github.com/yedidiaSch/pandion/releases/download/v#{version}/pandion_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "7a2fcb123a2f8b6b1a6ad5955ec4ea60dff293732b2aef5095a439bb16e2f993"
      url "https://github.com/yedidiaSch/pandion/releases/download/v#{version}/pandion_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "5401f91662511e649aa9a96f3f196c65a2cb17ac8e7c4ef4872028f196d9b0c8"
      url "https://github.com/yedidiaSch/pandion/releases/download/v#{version}/pandion_#{version}_linux_arm64.tar.gz"
    end
  end

  name "pandion"
  desc "Provision, harden & orchestrate C++/IPC dev environments"
  homepage "https://github.com/yedidiaSch/pandion"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pandion"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/pandion"]
    end
  end

  # No zap stanza required

end
