# This file was generated by GoReleaser. DO NOT EDIT.
cask "pandion" do
  version "0.7.0"

  on_macos do
    on_intel do
      sha256 "d51a1b5077cae927d9dda07dc6b2e6102b4f70e5291e90b7b3497cbbb0e8af49"
      url "https://github.com/yedidiaSch/pandion/releases/download/v#{version}/pandion_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "a5415b3d33ac241168e14d35d5e8b3def10da8a8a3037a52f95dc2c1eda45520"
      url "https://github.com/yedidiaSch/pandion/releases/download/v#{version}/pandion_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "7cba1a67e42cf10d614f34622b17874f09f25a2ffa536d02234d011348b0f9ef"
      url "https://github.com/yedidiaSch/pandion/releases/download/v#{version}/pandion_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "5b1a6021bc9aecae66bfa1e1aa36cd84877151691a6422faf13a46f16dda0e2c"
      url "https://github.com/yedidiaSch/pandion/releases/download/v#{version}/pandion_#{version}_linux_arm64.tar.gz"
    end
  end

  name "pandion"
  desc "Provision, harden & orchestrate C++/IPC dev environments"
  homepage "https://github.com/yedidiaSch/pandion"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pandion"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/pandion"]
    end
  end

  # No zap stanza required

end
